name = "D"
entrypoint = "main.d"

extensions = [
  "d",
  "dlang",
]

packages = [
  "gdc",
  "gdb"
]

[compile]
command = [
  "gdc",
  "-g",
  "main.d"
]

[run]
  command = [
  "./main"
  ]

[tests]
  [tests.hello]
    code="import std.stdio: writeln;void main(){writeln(\"hello\");}"
    output="hello\n"
    
